kind: Deployment
apiVersion: apps/v1
metadata:
  name: mag-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mag-sample
  template:
    metadata:
      labels:
        app: mag-sample
    spec:
      containers:
        - name: mag-sample
          image: sample-dict/mag-sample
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # resources limits
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: mag-sample
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: mag-sample
